- name: "Type: Bug"
  color: "e80c0c"
  description: "Something isn't working as expected."

- name: "Type: Documentation"
  color: "2fbceb"
  description: "Documentation is missing, unclear or incorrect."

- name: "Type: Feature"
  color: "54b2ff"
  description: "A new feature or capability."

- name: "Type: Security"
  color: "fbff00"
  description: "Security-related work or remediation."

- name: "Type: Question"
  color: "9309ab"
  description: "A question or support request."

- name: "Type: Dependency"
  color: "54b2ff"
  description: "Dependency related issue or PR."

- name: "Status: Awaiting Review"
  color: "24d15d"
  description: "Ready for review."

- name: "Status: WIP"
  color: "07b340"
  description: "Currently being worked on."

- name: "Status: Waiting"
  color: "38c968"
  description: "Waiting on another action or dependency."

- name: "Status: Stale"
  color: "66b38a"
  description: "Has had no activity for some time."

- name: "Priority: Critical"
  color: "ff008c"
  description: "Task is considered critical."

- name: "Priority: High"
  color: "8a0b1e"
  description: "Task is considered high priority."

- name: "Priority: Medium"
  color: "ffa500"
  description: "Task is considered medium priority."

- name: "Priority: Low"
  color: "690a34"
  description: "Task is considered low priority."

- name: "Duplicate"
  color: "eb862d"
  description: "Duplicate of another issue."

- name: "Invalid"
  color: "faef50"
  description: "Issue is invalid or cannot be reproduced."

- name: "Won't fix"
  color: "c8d9e6"
  description: "Issue will not be addressed."

- name: "3rd party issue"
  color: "e88707"
  description: "Caused by an external package or dependency."

- name: "OS: Windows"
  color: "aeb1c2"
  description: "Windows-specific."

- name: "OS: Mac"
  color: "aeb1c2"
  description: "macOS-specific."

- name: "OS: Linux"
  color: "aeb1c2"
  description: "Linux-specific."
